require 'active_support'
require 'active_support/core_ext'
require "sprites/version"

require 'forwardable'

class Sprites
  extend ActiveSupport::Autoload

  autoload :Configuration
  autoload :Sprite
  autoload :SpritePieces
  autoload :SpritePiece
  autoload :Stylesheet
  autoload :ChunkyPngGenerator, 'sprites/sprite_generators/chunky_png_generator'

  include Enumerable
  extend Forwardable
  def_delegators :@sprites, :clear, :empty?, :count, :[]

  attr_reader :configuration

  def initialize(configuration = Configuration.new)
    @configuration = configuration

    @sprites = Hash.new do |sprites, name|
      sprites[name] = Sprite.new(name, self)
    end
    @loaded = false
  end

  def [](sprite_identifier)
    @sprites[sprite_identifier] if @sprites.has_key?(sprite_identifier)
  end

  def each(&blk)
    @sprites.values.each(&blk)
  end

  def configure(options)
    configuration.configure(options)
  end

  # The +sprite+ method adds sprites to the sprites collection
  #
  # === Examples ===
  # sprite :foo
  # sprite :foo, :orientation => :horizontal, :css_prefix => '.foo '
  #
  # options:
  # => :orientation - sprite orientation
  #       default:  :vertical
  # => :path - path to which to write the sprite relative to config.sprites_path
  #       default:  public/images/sprites/{name}.png
  # => :stylesheet_path - path to which to write the stylesheet relative to config.sprite_stylesheets_path
  #       default:  public/stylesheets/sprites/{name}.css
  # => :url - path to use in background attribute in stylesheet
  #       default:  /images/sprites/{name}.png
  # => :autoload - whether or not to auto-define the sprite based on directory contents
  #       default: true
  # => :css_prefix - a css string to prepend to all css classes define or autogenerated
  #       examples: '.icon', '.contacts '
  #       default: ''
  #
  def sprite(name, options = {}, &blk)
    sprite = @sprites[name.to_sym]
    sprite.configure(options, &blk)
  end

  def add(sprite)
    @sprites[sprite.name] = sprite
  end

  def loaded?
    @loaded
  end

  def load
    return if loaded?
    if configuration.definition_file
      load_file configuration.definition_file
    elsif configuration.autoload
      auto_load
    end
    @loaded = true
  end

  def auto_load
    Dir[File.join(configuration.sprite_pieces_path, '*')].each do |sprite_path|
      sprite(File.basename(sprite_path).intern) if File.directory?(sprite_path)
    end
  end

  def load_file(path)
    instance_eval File.read(path), path, 0    
  end

  alias define instance_eval
  public :define

  def reset!
    clear
    @configuration = Configuration.new
    @loaded = false
  end

  def all_files
    files = {}

    all_files = []
    if configuration.definition_file
      files[configuration.definition_file] = all_files
    end

    @sprites.each do |name, sprite|
      all_files.concat sprite.all_sprite_piece_files
      files[sprite.stylesheet_path] = sprite.all_sprite_piece_files
      files[sprite.path] = sprite.all_sprite_piece_files
    end

    all_files.uniq!

    files
  end

  def generate(generator = configuration.generator)
    generator.new(self).generate
  end

  def define_file_tasks(task_name = :sprites)
    extend Rake::DSL
    all_files.each do |output, inputs|
      FileList[inputs]
      file output => inputs do
        generate
      end
    end
    task task_name => all_files.keys
  end
end

require 'sprites/railtie' if defined?(Rails)
